---
title: "04_estimation"
author: "Greg Macfarlane"
date: "6/17/2019"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(cache = TRUE)
library(tidyverse)
library(sf)
library(spatialreg)
library(texreg)
```

We load the data prepared previously. There is a file for each park and its 
attribute, for each tract and its attributes, and the distance matrix between 
parks and tracts.

```{r loaddata}
tracts_access <- read_rds("data/tracts_acces.rds")
W <- read_rds("data/W.rds")
trMC <- trMC <- trW(as(W, "CsparseMatrix"), type="MC")
tracts_sp <- as(tracts_access, "Spatial")
```





```{r base_formula}
base_formula <- formula(
  ~ log(density) + log(income) +
    fulltime + college + single +
    youth + young_adults + seniors + # need to leave out a category for collinearity
    black + asian + hispanic + other)
```


```{r spatial selection}
physact_base_sem <- errorsarlm(update(base_formula, physact ~ .),
                               data = tracts_sp, listw = W, zero.policy = TRUE)
physact_base_sdm <- lagsarlm(update(base_formula, physact ~ .),
                             data = tracts_sp, listw = W, zero.policy = TRUE,
                             type = "mixed")
test_sdmsem <- lmtest::lrtest(physact_base_sem, physact_base_sdm)
```

```{r access_sdm}
# estimate models
pa_access_sem <- update(physact_base_sem, .~ . + access_ls)
pa_quarter_sem <- update(physact_base_sem, .~ . + walk_10)

pa_models <- list("Base" = physact_base_sem,
                  "Access: logsum" = pa_access_sem,
                  "Access: 10-min walk" = pa_quarter_sem)
```

```{r screen_pa_models}
view_kable(
htmlreg(pa_models, digits = 4, table = FALSE, single.row = TRUE, 
                   caption.above = TRUE, caption = "Spatial Error Model ",
          stars = c(0.001, 0.01, 0.05, 0.1) )
)
```

```{r}
view_kable <- function(x){
  tab <- paste(capture.output(x))
  tf <- tempfile(fileext = ".html")
  writeLines(tab, tf)
  viewer <- getOption("viewer")
  viewer(tf)
}
```


```{r obesity_models}
obesity_models <- lapply(pa_models, function(model){
  update(update(model, obesity ~ . + physact))
})

names(obesity_models) <- names(pa_models)
```

```{r screen_obesity_models}
screenreg(obesity_models, digits = 4, table = FALSE)
```

```{r screen_obese_models, eval = FALSE}
  screenreg(obesity_models, digits = 4, table = FALSE, ci.force = TRUE,
          single.row = TRUE, caption = "Spatial Error Model Estimates of Effect on Obesity Rates",
          caption.above = TRUE, custom.coef.names = c(
            "(Intercept)", "log(Density)", "log(Income)",
            "Fulltime", "College-educated",  "Single Adults",
            "Youth (0-17)", "Young adults (18-34)",
            "Seniors (65+)", "Black population share",
            "Asian population share",
            "Hispanic population share", "Other Minorities",
            "Physical activity",
            "Spatial correlation", "Access: Logsum", "Access: 10-min walk"
          ))
```

```{r obesityplot}
names_for_terms <- c(
  "(Intercept)", "log(density)", "log(Income)",
  "Fulltime", "College-educated",  "Single Adults",
  "Youth (0-17)", "Young adults (18-34)",
  "Seniors (65+)", "Black population share",
  "Asian population share",
  "Hispanic population share", "Other Minorities",
  "$\\gamma$: spatial correlation","Physical activity",
  "Access: Logsum", "Access: 10-min walk"
)
termnames <- tibble(
  name = names_for_terms,
  term = c("Intercept", "log(density)", "log(income)", "fulltime", "college", "single",
           "youth", "young_adults", "seniors", "black", "asian", "hispanic", "other",
           "lag", "physact", "access_ls", "walk_10TRUE"))
source("R/impacts_extractor.R")
obesity_impacts <- lapply(obesity_models, function(x) impacts_extractor(x, trMC)) %>%
  bind_rows(.id = "model")  %>%
  left_join(termnames, by = "term") %>%
  mutate(name = factor(name, levels = rev(names_for_terms)))

ggplot(obesity_impacts %>% filter(effect == "Total"), 
       aes(x = name, ymin = `2.5%`, ymax = `97.5%`,  y = `50%`, color = model)) +
  geom_abline(slope = 0, intercept = 0, color = "gray") +
  geom_errorbar(position = "dodge2") +
  scale_color_brewer("Model", palette = "Set1") +
  #geom_point(position = "dodge2") +
  ylab("Simulated Total Impact on Obesity Rate") +
  coord_flip() +
  #facet_wrap(~effect) +
  theme_bw() +
  theme(legend.position = "bottom", 
        axis.text.y = element_text(size = 10),
        axis.title.y = element_blank())
```
